### PR TITLE
Enable GC.auto_compact in test suite

### PR DESCRIPTION
**Pull request by casperisfine**
Reproduces: https://github.com/jhawthorn/vernier/issues/100

cc @jhawthorn

### CODE REVIEW

**Comment by casperisfine** [comment]
https://github.com/jhawthorn/vernier/pull/101/commits/5b0579fa3a568629b2ddd2ec44ffa4dcc3190303 fixes the crash, but now some tests are failing.

I don't really have quite the full context here to know what else may be missing.

**Comment by joshuay03** [comment]
> [5b0579f](https://github.com/jhawthorn/vernier/commit/5b0579fa3a568629b2ddd2ec44ffa4dcc3190303) fixes the crash, but now some tests are failing.
> 
> I don't really have quite the full context here to know what else may be missing.

a4babd8c54ecd3a54184356a605e3c360e918060 seems to have sorted it out 👍🏽

**Comment by casperisfine** [comment]
Oh thank you so much (I'm really not familiar with C++).

**Comment by joshuay03** [comment]
> Oh thank you so much (I'm really not familiar with C++).

No worries, I’m still getting the hang of it too. It’d be preferable to have @jhawthorn’s sign-off on this.

**Comment by jhawthorn** [comment]
Thanks! I didn't know y'all were using retained profiling that's cool.

Auto compaction seemed to reproduce this consistently but I added an explicit test using verify_compaction_references in 702b1398350c9c64887af048f37e0fbca68ee8fe to be sure

**Pull request merged**
